<?php
    unset($_SESSION['uid']);
    unset($_SESSION['user']);
    unset($_SESSION['uname']);
    unset($_SESSION['perm']);
    unset($_SESSION['filters']);
    session_unset();
    redirect(url('login'));
?>